# Generated by Django 5.1.6 on 2025-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

  

    operations = [
        
        migrations.AddField(
            model_name='post',
            name='coursetitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
